### ISSUE TITLE
zope.testrunner (5.3.0) integration broken: AttributeError: module 'zope.testrunner' has no attribute 'runner'

### ISSUE THREAD

**Issue by mgorny** [flexmock/flexmock#100]
This can be easily reproduced by forcing `zope.testrunner` into the tox test env:

```diff
diff --git a/tox.ini b/tox.ini
index 74c0c36..5b188e6 100644
--- a/tox.ini
+++ b/tox.ini
@@ -20,6 +20,7 @@ deps =
     pytest6: pytest>=6.0,<7.0
     pytest-latest: pytest
     twisted
+    zope.testrunner
 commands =
     python -m unittest tests/flexmock_test.py
     python -c "from twisted.scripts.trial import run; run();" tests/flexmock_test.py
```

The resulting failure:
```pytb
$ tox -e py39-pytest-latest
py39-pytest-latest recreate: /tmp/flexmock/.tox/py39-pytest-latest
py39-pytest-latest installdeps: pytest, twisted, zope.testrunner
py39-pytest-latest inst: /tmp/flexmock/.tox/.tmp/package/1/flexmock-0.11.0.tar.gz
py39-pytest-latest installed: attrs==21.2.0,Automat==20.2.0,constantly==15.1.0,flexmock @ file:///tmp/flexmock/.tox/.tmp/package/1/flexmock-0.11.0.tar.gz,hyperlink==21.0.0,idna==3.3,incremental==21.3.0,iniconfig==1.1.1,packaging==21.2,pluggy==1.0.0,py==1.11.0,pyparsing==2.4.7,pytest==6.2.5,six==1.16.0,toml==0.10.2,Twisted==21.7.0,typing-extensions==3.10.0.2,zope.exceptions==4.4,zope.interface==5.4.0,zope.testrunner==5.3.0
py39-pytest-latest run-test-pre: PYTHONHASHSEED='1072236296'
py39-pytest-latest run-test: commands[0] | python -m unittest tests/flexmock_test.py
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.9/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.9/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/lib/python3.9/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/usr/lib/python3.9/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.9/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/flexmock/tests/flexmock_test.py", line 12, in <module>
    from flexmock._api import (
  File "/tmp/flexmock/.tox/py39-pytest-latest/lib/python3.9/site-packages/flexmock/__init__.py", line 2, in <module>
    from flexmock import _integrations  # pylint: disable=unused-import
  File "/tmp/flexmock/.tox/py39-pytest-latest/lib/python3.9/site-packages/flexmock/_integrations.py", line 181, in <module>
    _patch_test_result(testrunner.runner.TestResult)
AttributeError: module 'zope.testrunner' has no attribute 'runner'
ERROR: InvocationError for command /tmp/flexmock/.tox/py39-pytest-latest/bin/python -m unittest tests/flexmock_test.py (exited with code 1)
```

**Comment by ollipa** [comment]
Thank you for the bug report! It seems that this exception was silently ignored in the previous release so I wonder how the integration was working before.

Pre 0.11.0:
```python
def _hook_into_zope():
    try:
        from zope import testrunner
        _patch_test_result(testrunner.runner.TestResult)
    except:
        pass
_hook_into_zope()
```

0.11.0:
```python
with suppress(ImportError):
    from zope import testrunner  # pylint: disable=no-name-in-module

    _patch_test_result(testrunner.runner.TestResult)
```

**Comment by mgorny** [comment]
It probably didn't. I've only noticed because tests started failing on me now.

**Comment by ollipa** [comment]
Ignoring the error was actually intended behavior. It seems that `zope.testrunner.runner` is only available when the test runner is executed so if the tests are executed with some other test runner, an exception would be raised. PR #101 fixes this bug and adds Zope testrunner to our test suite.
