### ISSUE TITLE
Pytest 8.1.0 removed _pytest.runner.call_runtest_hook

### ISSUE THREAD

**Issue by tvuotila** [flexmock/flexmock#152]
Newest pytest removed the `_pytest.runner.call_runtest_hook`, which flexmock depends on.

```
*****************
Running unittest
*****************
PYTHONPATH=/Users/tvuotila/flexmock python3 tests/test_unittest.py
Traceback (most recent call last):
  File "/Users/tvuotila/flexmock/tests/test_unittest.py", line 6, in <module>
    from flexmock import flexmock
  File "/Users/tvuotila/Library/Caches/pypoetry/virtualenvs/flexmock-RTiH4lMC-py3.12/lib/python3.12/site-packages/flexmock/__init__.py", line 2, in <module>
    from flexmock import _integrations  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tvuotila/Library/Caches/pypoetry/virtualenvs/flexmock-RTiH4lMC-py3.12/lib/python3.12/site-packages/flexmock/_integrations.py", line 101, in <module>
    saved_pytest = runner.call_runtest_hook
                   ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module '_pytest.runner' has no attribute 'call_runtest_hook'
make: *** [unittest] Error 1
```

Reproduction:
```
pip install pytest==8.1.0
make test
```

Note: pytest >7.4.2 depends on Python >=3.8 and flexmock supported Python version range is ^3.7.1. Thus, `poetry update pytest` won't install the newest pytest.

**Comment by ollipa** [comment]
Thanks for reporting the issue! I think we could use pytest plugin system instead of monkey patching. That has been working well in chainmock.

See:
https://github.com/ollipa/chainmock/blob/main/src/chainmock/_pytest_plugin.py

What do you think @christophe-riolo, @adarshk7 ?

**Comment by christophe-riolo** [comment]
I agree, I don't think monkey patching is a good long term solution :+1:
